### ISSUE TITLE
Sanitize newlines when generating Markdown tables

### ISSUE THREAD

**Issue by alex-ketch** [stencila/encoda#179]
When generating Markdown tables, if the content includes a newline (`\n`), it gets printed and breaks the table formatting.
This is causing immediate problems for generating Schema Documentation (please see the attached image below):

<img width="608" alt="Screen-Shot-2019-07-20-at-8 35 40-AM" src="https://user-images.githubusercontent.com/1646307/61827365-59d15680-ae32-11e9-9606-710098ae1d57.png">

**Comment by nokome** [comment]
Because Markdown is essentially a newline sensitive format, that the best way to deal with this is to replace newlines with a space (I think we use `.replace(/\s+/, ' ')` elsewhere) when encoding `string` nodes:

https://github.com/stencila/encoda/blob/ff867470722c890ce4f21706e890751f587bdb7b/src/codecs/md/index.ts#L955-L960
