### ISSUE TITLE
HTML: Deprecate usage of <stencila-*> custom elements

### ISSUE THREAD

**Issue by alex-ketch** [stencila/encoda#244]
> With respect to `<stencila-thing>` and the other custom elements: given that we are moving to using Microdata, IMO we should not use these anymore. They were intended to provide additional semantics for content (a) for machine readability, (b) for progressive enhancement via web components. But using semantic elements e.g. `<time>` and Microdata is better for (a) and can still be used for (b) (by parsing the DOM for `itemtype` etc). 

_Originally posted by @nokome in https://github.com/stencila/encoda/pull/233#issuecomment-523666817_

Instead we should enrich elements using [MircoData](https://www.w3.org/TR/microdata/) `itemtype` and `itemprop` attributes.

**Comment by nokome** [comment]
Just to note that we have now reversed this decision because custom elements provide the most robust means to support progressive enhancement via Web Components. 

Many of the changes in commit 3faa828914e64bbbd4635dff3a19112c5f629a82 will need to be reverted so that we have a consistent approach of using custom elements e.g. `<stencila-datatable>` for any node that does not have a corresponding semantic node in HTML and/or which a Web Component is desired **combined with** Microdata enrichment for any node that we want to encourage machine readability.
