### ISSUE TITLE
RPNGs generated by for Executa are too wide

### ISSUE THREAD

**Issue by alex-ketch** [stencila/encoda#545]
They should only be as wide as necessary

<img width="869" alt="CleanShot 2020-05-12 at 09 49 29@2x" src="https://user-images.githubusercontent.com/1646307/81699896-f6063180-9435-11ea-89bb-e227c8733ac8.png">

**Comment by nokome** [comment]
Some longstanding UI issues we may want to address at the same time:

- no visual affordance on math nodes - it is not obvious that this is a node that I can edit, as opposed to an ordinary image.
- affordance on code chunk is relatively "heavy" - I imagine something more subtle but which directly links to the Stencila add-on - no background, not border, just a small Stencila icon in the corner with low opacity (i.e. a watermark)

In the first instance I suggest making these changes to the `prng` theme, but there is no reason we can't have `rpng-gdoc` etc themes for different contexts.

**Comment by nokome** [comment]
The cause of this issue is not the generation of the screenshot by the `PngCodec` but the interaction between the HTML (generated by the `HtmlCodec`) and the CSS (in the `rpng` theme)., specifically the placement of the `data-itemscope="root"` attribute.

The HTML generated for a standalone `CodeChunk` is this:

```html
  <body>
    <main role="main">
      <stencila-code-chunk itemscope="" itemtype="http://schema.stenci.la/CodeChunk"
        data-programminglanguage="r" data-itemscope="root">
        <pre class="language-r" itemscope="" itemtype="http://schema.stenci.la/CodeBlock"
          slot="text"><code># Just a comment
</code></pre>
      </stencila-code-chunk>
    </main>
  </body>
```

which renders in the browser as:

![image](https://user-images.githubusercontent.com/1152336/82282245-79e88c80-99e7-11ea-85df-cbdee67dfe6c.png)

However, if the `data-itemscope="root"` is moved to the `main` element,

```html
  <body>
    <main role="main" data-itemscope="root">
      <stencila-code-chunk itemscope="" itemtype="http://schema.stenci.la/CodeChunk"
        data-programminglanguage="r">
        <pre class="language-r" itemscope="" itemtype="http://schema.stenci.la/CodeBlock"
          slot="text"><code># Just a comment
</code></pre>
      </stencila-code-chunk>
    </main>
  </body>
```

then it renders as:

![image](https://user-images.githubusercontent.com/1152336/82282186-5291bf80-99e7-11ea-82cb-35432da4a349.png)

I have made a fix by wrapping non creative nodes before generating the HTML (below), but do wonder if a safer fix would be to change the CSS.

```js
    // If the node is not a creative work then wrap
    // it in one. This is done because themes usually assume that
    // nodes such as `Paragraph`, `CodeChunk` etc are not the root
    // node but are instead nested within another node that is the root.
    if (!schema.isCreativeWork(node)) {
      node = schema.creativeWork({content: [node]})
    }
```
