### ISSUE TITLE
Reduce brand tone on default output themes

### ISSUE THREAD

**Issue by alex-ketch** [stencila/encoda#62]
> The Word and HTML styling is too garish for my tastes and as a user the very first thing I would do is go and change the styles - particularly of the headings. But I think we should discuss that in another PR. 
> https://github.com/stencila/convert/pull/59#pullrequestreview-237620337
:)

The current default themes are based on the Stencila website which, while great for marketing materials, is a little too harsh and distracting for consumption of prose/long-form content.

We'd like to turn down the volume on the branding, the objective being for generated documents to remain identifiable as coming from Stencila without distracting from the content.

**Comment by nokome** [comment]
Yesterday a user found that when opening the encoded Word document, the font displayed was cursive. That was probably because the font used in the current word template (Nunito) was not available on their machine. So as part of generating a new Word template we should try to use a font that is more widely available, or has similar fallbacks?
