### ISSUE TITLE
Remove deprecated schema properties from `xlsx` converter

### ISSUE THREAD

**Issue by alex-ketch** [stencila/encoda#63]
> :+1: This will require an change in the `xlsx` converter. https://github.com/stencila/convert/blob/master/src/xlsx.ts#L121-L161

_Originally posted by @nokome in https://github.com/stencila/schema/pull/59_

The following properties have been removed from Schemas:
- Table: `cells`
- TableCell: `position`

**Comment by nokome** [comment]
To clarify a little more. We used to allow a `Table` to have either `cells` (a mapping of cell ids e.g. `A3` to their value) or `rows`. Having these two options was convenient for this `xlsx` codec but is inconvenient for others e.g. `html` (because it means another code branch to handle). So we decided to make `Table`s row based only (to complement the column based `Datatable`s).

The downside of this is that row-based HTML-style data model for tables is not efficient for sparse tables (like spreadsheets can be) (the `cells` approach was great for that). Nonethless, I think we can optimise that in the future with properties on `TableCell` - something similar to `colspan` but which indicates the size of the column gap to the next cell - `colskip`?
