### ISSUE TITLE
Handle escaped string while parsing CSVs

### ISSUE THREAD

**Issue by alex-ketch** [stencila/encoda#66]
https://github.com/stencila/convert/blob/ff0d789081b46788ac5df1043505300fda90c806/src/util.ts#L171-L176

> Unfortunately this does not account for escaped text like:
> ``` csv
> header1, header2, header3
> text, "some text, it contains a comma", another text 
> ```

_Originally posted by @alex-ketch in https://github.com/stencila/convert/pull/65_

**Comment by nokome** [comment]
I set out to quickly create an test to show that this wan't a problem and ended up going down somewhat of a rabbit hole. The following commits document the process:

- Even though the `csv` codec was not using the linked to line, there did indeed appear to be a problem with the handling of quoted values: https://github.com/stencila/encoda/commit/d12bc5a454034ba4b00c7c0fbd976cae9d49482b

- After using another CSV parsing library it seems that is actually expected behaviour (not confirmed) associated with having spaces after commas: https://github.com/stencila/encoda/commit/f8c8e0ea91e9fe7106ffa518e4719ed1225dc089

- Since I had already adapted to another library, this commit uses `papaparse` on the assumption that as a dedicated CSV parsing / serializing library it will have more options (likely, based on docs) and better perfromance (untested) than `js-xlsx`: https://github.com/stencila/encoda/commit/e03abc12167cb23e627c48250fdcd5b68d6b0843

@alex-ketch : let me know if you think we should go ahead and use `papaparse` here

**Comment by alex-ketch** [comment]
Thanks for the in-depth investigation @nokome! 🕵
I think the whitespace inclusion in headers/content makes sense given that anything between the delimiter is supposedly content.
The usage of `papaparse` looks good though, and I like the functionalities and promises it brings 👍

**Comment by nokome** [comment]
OK, I'll go ahead and merge the.
