### ISSUE TITLE
md to docx: output path requires `./`

### ISSUE THREAD

**Issue by jwijay** [stencila/encoda#90]
![Screenshot 2019-06-05 11 29 16](https://user-images.githubusercontent.com/10161095/58980535-6e279a00-8785-11e9-8971-ccc8eb92384c.png)

Probably a low-priority issue. When using encoda, the output path requires a `./`, and the error points to a missing codec rather than the path format.

e.g. passing:
`npx ts-node --files src/cli convert examples/R-ecology-lesson/README.md ./examples/output/README.docx`

but failing:
`npx ts-node --files src/cli convert examples/R-ecology-lesson/README.md examples/output/README.docx`

**Comment by beneboy** [comment]
I went to fix this but the code only assumes it's a path if it starts with` `/, `./` or` ../`. Or if the file at that path exists (which the output file won't).

https://github.com/stencila/encoda/blob/0a771d4b46c9dac6fd95c81502b4a037a1b5bcb7/src/vfile.ts#L99
```
If the string starts with `/`, `./`, `../` (or Windows compatible backslash
```

I will defer to @nokome for input. On one hand I think detecting of the file could be better but also since this interface is only for devs maybe it doesn't matter. Perhaps just a message like 'if $path is a path, please prefix it with ./'

**Comment by nokome** [comment]
This isn't only for devs because the same function gets used in `stencila` too. The aim is to allow the user to be able to write content or a file path at the CLI. Putting content on the CLI may not seem that that useful if you only think about doing file conversions. But for demoing and testing encodings it can be useful e.g.

```
npx ts-node --files src/cli convert "{type: 'CodeBlock'}" test.png --from json5 --to rpng
```

So the point of `isPath` is to guess if the user intended to specify a file path. I'd prefer to keep it like that.

But we need to improve it's guessing - I think by detecting if it's got an extension - like we do here: https://github.com/stencila/stencila/blob/master/src/commands/convert.ts#L79
